# Generated by Django 3.1.2 on 2020-10-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='name',
            field=models.CharField(db_index=True, max_length=120, unique=True),
        ),
    ]
