# Generated by Django 3.1.2 on 2020-10-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompter', '0002_auto_20201019_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='name',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('mode', 'name', 'frequency')},
        ),
    ]
