# Generated by Django 3.1.2 on 2020-10-26 20:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompter', '0003_auto_20201019_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='frequency',
            field=models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
