# Generated by Django 3.1.2 on 2020-10-27 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prompter', '0004_auto_20201026_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='frequency',
            new_name='importance',
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('mode', 'name', 'importance')},
        ),
    ]
