# Generated by Django 3.1.2 on 2020-10-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompter', '0005_auto_20201027_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='use',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('mode', 'name', 'importance', 'use')},
        ),
    ]
